// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalDashboard.Api.Data;

#nullable disable

namespace PersonalDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610222228_AddGoalCompletedOn")]
    partial class AddGoalCompletedOn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ExpectedHigh")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExpectedLow")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("ForDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.BingoBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BingoBoards");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.BingoSquare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Position")
                        .IsUnique();

                    b.ToTable("BingoSquares");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.CalendarEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("boolean");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("StartsAt");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.DailyTodo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("DailyTodos");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Name")
                        .IsUnique();

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.FoodEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<double>("CalciumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsG")
                        .HasColumnType("double precision");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision");

                    b.Property<double>("FiberG")
                        .HasColumnType("double precision");

                    b.Property<double?>("Grams")
                        .HasColumnType("double precision");

                    b.Property<double>("IronMg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Meal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PotassiumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<double>("SatFatG")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingDescription")
                        .HasColumnType("text");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("SugarG")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("Date");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorHex")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CompletedOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.GoalSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("GoalId", "HabitId")
                        .IsUnique();

                    b.ToTable("GoalSources");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetPerPeriod")
                        .HasColumnType("integer");

                    b.Property<bool>("TracksTime")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.HabitLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "Date")
                        .IsUnique();

                    b.ToTable("HabitLogs");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetricKey", "RecordedAt");

                    b.HasIndex("DataSourceId", "MetricKey", "RecordedAt")
                        .IsUnique();

                    b.ToTable("MetricSamples");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.MusicPlay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PlayedAt");

                    b.ToTable("MusicPlays");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.QuickMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultMeal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuickMeals");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.QuickMealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<double>("CalciumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsG")
                        .HasColumnType("double precision");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision");

                    b.Property<double>("FiberG")
                        .HasColumnType("double precision");

                    b.Property<double?>("Grams")
                        .HasColumnType("double precision");

                    b.Property<double>("IronMg")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PotassiumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("QuickMealId")
                        .HasColumnType("integer");

                    b.Property<double>("SatFatG")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingDescription")
                        .HasColumnType("text");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("SugarG")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("QuickMealId");

                    b.ToTable("QuickMealItems");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.SavedFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<double>("CalciumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsG")
                        .HasColumnType("double precision");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<double>("DefaultQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<double>("FiberG")
                        .HasColumnType("double precision");

                    b.Property<double?>("Grams")
                        .HasColumnType("double precision");

                    b.Property<double>("IronMg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PotassiumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision");

                    b.Property<double>("SatFatG")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingDescription")
                        .HasColumnType("text");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("double precision");

                    b.Property<double>("SugarG")
                        .HasColumnType("double precision");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Brand", "ExternalRef")
                        .IsUnique();

                    b.ToTable("SavedFoods");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.ScheduleBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Protected")
                        .HasColumnType("boolean");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Day", "StartMinutes");

                    b.ToTable("ScheduleBlocks");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("StartedAt");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.BingoSquare", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.BingoBoard", "Board")
                        .WithMany("Squares")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.CalendarEvent", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.FoodEntry", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.GoalSource", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.Goal", "Goal")
                        .WithMany("Sources")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalDashboard.Api.Domain.Habit", "Habit")
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.HabitLog", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.Habit", "Habit")
                        .WithMany("Logs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.MetricSample", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.MusicPlay", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.QuickMealItem", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.QuickMeal", "QuickMeal")
                        .WithMany("Items")
                        .HasForeignKey("QuickMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuickMeal");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Workout", b =>
                {
                    b.HasOne("PersonalDashboard.Api.Domain.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.BingoBoard", b =>
                {
                    b.Navigation("Squares");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Goal", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.Habit", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PersonalDashboard.Api.Domain.QuickMeal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
